---
- name: Add user to htpasswd
  command: "htpasswd -b {{htpasswd_path}} {{user.name}} {{user.password}}"
  delegate_to: "{{master_public_ip}}"
  remote_user: "{{amazon_user}}"
  become: true
  
- name: Cluster admin rights
  command: "oadm policy add-cluster-role-to-user cluster-admin {{user.name}}"
  when: user.admin
  delegate_to: "{{master_public_ip}}"
  remote_user: "{{amazon_user}}"  